// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package source

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigPortBindings = "portBindings"
	ConfigTopic        = "topic"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigPortBindings: {
			Default:     "",
			Description: "PortBindings is a comma separated list of ports that we wish to bind to",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigTopic: {
			Default:     "",
			Description: "Topic is the topic to publish to when receiving a record to write",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
